### PR TITLE
Add "Project Fuse ⚡️" label

### PR DESCRIPTION
**Pull request by barrymcgee**

### CODE REVIEW

**Comment by anthonydillon** [comment]
What is the rationale behind the project fuse label? Is it a priority or just for filtering?

**Comment by barrymcgee** [comment]
Yes, filtering.

**Comment by anthonydillon** [comment]
This raise a interesting question. Which squad should project fuse fall under? Would it be an epic of epics or an on going effect? You see that would be my recommend method of filtering. 

In theory, I have nothing against adding labels but this would be an odd ball which I struggle with, with my OCD.

**Comment by barrymcgee** [comment]
@anthonydillon As it doesn't have a start or end date, I didn't think it would lend itself very well to an epic. 

I see it as a thread that should run through all projects but needs a little help to increase its visibility. This label will mean we can do a couple of things;

- Add it to issues on repos and then collate them all via a filter to share with squad leads.
- Act as a constant visual reminder to contributors that 'Project Fuse'/Performance is a thing and should be constantly considered.

The labels already follow an inconsistent format so this isn't a sole outlier.

**Review by anthonydillon — APPROVED** [review]
Ok, lets try it as a treadled task.

**Pull request merged**
